### ISSUE TITLE
Is that using transfer learning

### ISSUE THREAD

**Issue by themoonboy** [unit8co/amld-workshop-pneumonia#4]
I see a tag "transfer learning" in your repository, but for the 3rd project https://github.com/unit8co/amld-workshop-pneumonia/tree/master/3_pneumonia, is that including transfer learning, or just build a blank model and train it from beginning? Thanks!

**Comment by Digma** [comment]
hi @themoonboy,

If you look at the line

```python
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(150, 150, 3))
```

You can see that we are loading a VGG16 network with weights trained on `imagenet`. From that point on, the model has the weights and we are not training the model from scratch
